### ISSUE TITLE
Error while running COSMOS tutorial in R

### ISSUE THREAD

**Issue by dilipgosar** [saezlab/cosmosR#19]
Dear Sir/ Madam,

I am trying to run tutorial mentioned on COMSOS website but it is giving me this error.
> test_result_back <- format_COSMOS_res(test_result_back,
+                                       metab_mapping = metabolite_to_pubchem,
+                                       measured_nodes = unique(c(names(toy_metabolic_input),
+                                                                 names(toy_signaling_input))),
+                                       omnipath_ptm = omnipath_ptm)
Error in as.data.frame(cosmos_res$weightedSIF) : 
  object 'test_result_back' not found

I am running the R code exactly mentioned in the tutorial and I like to know if you can fix it.  Also I like to know if you can provide more examples of how to use COSMOS.

Appreciate your help.

Sincerely,

Dilip Gosar

**Comment by gabora** [comment]
tutorial is now updated. 
the github page will be updated in 4-5 mins.

**Comment by dilipgosar** [comment]
Hello Attila,

Thank you for your reply. I was trying to find the cosmosR package vignette but could not find it. It is giving me one more error. I have loaded the cosmosR library in R. Then I was running the following code
> CARNIVAL_options <- default_CARNIVAL_options(solver = "lpSolve")
Error in default_CARNIVAL_options(solver = "lpSolve") : 
  unused argument (solver = "lpSolve")

I don't know what this error means. I like to know how you can help me.

Appreciate your help.

Sincerely,

Dilip Gosar

**Comment by gabora** [comment]
Hi,
that means you are not using the latest version, please update to cosmos v1.3, at least.

You can install from our github
```{r}
remotes::install_github("saezlab/cosmosR")
```
or 
from Bioconductor, 
```{r}
BiocManager::install("cosmosR")
```
 in this case make sure that your BiocManager is up to date (the current release is 3.15).

best
Attila
