### ISSUE TITLE
metabolic IDs seem to be  inconsistent

### ISSUE THREAD

**Issue by gabora** [saezlab/cosmosR#21]
Hi @adugourd ,

 
I found `Metab__HMDB0001514_c` and also `Metab__439213_c` in the PKN, but  based on this: 
https://hmdb.ca/metabolites/HMDB0001514 they both encode "D-Glucosamine". 

Unfortunately, in the PKN, they have different reaction partners, so they are not representing the same metabolite:

interactions based on HMBD: 
`> meta_network[meta_network$source=="Metab__HMDB0001514_c",]`

>                     source interaction                   target
> 48415 Metab__HMDB0001514_c          -1                     IL1B
> 81712 Metab__HMDB0001514_c           1            Gene9119__GCK
> 81714 Metab__HMDB0001514_c           1            Gene9119__HK2
> 81716 Metab__HMDB0001514_c           1            Gene9119__HK1
> 81718 Metab__HMDB0001514_c           1          Gene9119__HKDC1
> 81720 Metab__HMDB0001514_c           1            Gene9119__HK3
> 83913 Metab__HMDB0001514_c           1            Gene9717__HK1
> 83917 Metab__HMDB0001514_c           1            Gene9717__HK2
> 83921 Metab__HMDB0001514_c           1            Gene9717__HK3
> 83925 Metab__HMDB0001514_c           1            Gene9718__HK1
> 83929 Metab__HMDB0001514_c           1            Gene9718__HK2
> 83933 Metab__HMDB0001514_c           1            Gene9718__HK3
> 93661 Metab__HMDB0001514_c           1 Gene8990__SLC2A1_reverse
> 93663 Metab__HMDB0001514_c           1 Gene8990__SLC2A4_reverse
> 93665 Metab__HMDB0001514_c           1 Gene8990__SLC2A2_reverse

interactions based on PubChem id: 

`> meta_network[meta_network$source=="Metab__439213_c",]`
               source interaction target
35844 Metab__439213_c          -1   MMP9
47070 Metab__439213_c          -1  NFKB2

This seems to be inconsistent. How could be this solved? 
thanks
Attila

**Comment by adugourd** [comment]
ah I see, thanks for noticing this. The second one comes from STITCH db and the first one from HMDB. In theory I should have translated the 49213 to hmdb format as well, dont know what happened here. I will double check the STITCH part of the code ASAP !
