### ISSUE TITLE
error in Check Pertubations

### ISSUE THREAD

**Issue by narmadabc** [saezlab/cosmosR#29]
Since we are hitting a memory limit for the cplex solver
CPLEX> Saving results...
Error in solversFunctions$solve(carnivalOptions) : 
  CPLEX solution file is not found. CPLEX was likely interrupted (exceeding memory limit is the usual cause).
           Try to increase the available resources (memory) or reducing the PKN. 

we tried to reduce the size of the RNA_input but I am encountering this issue while running Cosmos

Error in checkPerturbations(perturbations, nodesPriorKnowledgeNetwork) : 
  None of your perturbations are in prior knowledge networks (PKN). 
                                   Check node identifiers in both perturbations and PKN objects

Can you please suggest a solution?

**Comment by gabora** [comment]
Based on the error messages you provided, it seems that you are encountering two separate issues. Let's address each one individually:

1. Memory Limit Error with CPLEX Solver:  
The error message suggests that you are hitting a memory limit while using the CPLEX solver. This is a common issue when solving large optimization problems. To resolve this, you can try the following solutions:  

- Increase the available memory resources: If you have control over the memory allocation for the solver, you can try increasing the memory limit to accommodate your problem size. This may involve modifying the configuration settings of the CPLEX solver or allocating more memory to the machine running the solver.

- Reduce the size of the problem: If increasing the memory is not feasible, you can try reducing the problem size. This could involve reducing the number of variables that contribute to the memory usage.

2. Perturbations Not Found in Prior Knowledge Networks (PKN):
The second error message suggests that the perturbations you are providing are not present in the prior knowledge networks (PKN). This means that the node identifiers in your perturbations do not match the nodes in the PKN. To address this issue, you can consider the following steps:

- Verify the node identifiers: Double-check the node identifiers in both the perturbations and the PKN objects. Ensure that they are consistent and match each other. Pay attention to any differences in capitalization, spacing, or special characters.

- Update perturbations or PKN: If you find any discrepancies between the node identifiers, you will need to update either the perturbations or the PKN to align them correctly. You can modify the perturbations to match the node identifiers in the PKN or update the PKN to include the missing nodes from the perturbations.

By addressing these two separate issues, you should be able to make progress with your code and resolve the encountered errors.

disclaimer: text was generated by GPT 3.5. content was checked and adjusted.

**Comment by narmadabc** [comment]
How to check the perturbations and the nodes in the PKN?

**Comment by narmadabc** [comment]
Thank you Aurelien, when I set the network depth parameter to 3 or 2 I encounter the second error again. I am trying with the NC160 sample dataset

Error in checkPerturbations(perturbations, nodesPriorKnowledgeNetwork) :
None of your perturbations are in prior knowledge networks (PKN).
Check node identifiers in both perturbations and PKN objects

How to check the node identifiers for comparing between perturbations and PKN objects?

**Comment by narmadabc** [comment]
I have increased the R studio memory limit to 1gb and still facing same issue. I will try with increasing
Here what is meant by perturbations (is it the signaling input and metab input files or something else).
Does the carnival flavour matter when there are no external perturbations like disease or drugs?

**Comment by adugourd** [comment]
Ah I see, 1Gb is actually pretty low for many cases. You may wanna try to increase it to at least 16Gb. 

the perturbations are simply the deregulated upstream nodes. In the case of the NCI 60 dataset, the upstream deregulated (the signaling input) are considered "perturbations". You shouldn't worry about Carnival flavour.
