### ISSUE TITLE
Use of lipidomics data on Cosmos

### ISSUE THREAD

**Issue by narmadabc** [saezlab/cosmosR#30]
Can we use new query datasets like lipidomics in addition to proteomics or metabolomics, create a new PKN for running on Cosmos?

**Comment by narmadabc** [comment]
How do we incorporate different data input for e.g., proteomics and lipidomics in the absence of transcriptomics.

What are the issues if we append it together with metab input. 

Is the RNA_input not being considered and only used to reconfirm dorothea's TF activity output?

**Comment by adugourd** [comment]
The RNA_input is used to prune the non-expressed genes from the PKN as well, in addition to re-confirm the TF activity-target coherence.

If you have only proteomic and lipids, then you probably should use the proteins as up-stream (e.g. signaling) inputs and lipids as downstream (e.g. metabolic) inputs. However, the current lipid coverage of cosmos is very limitted to some fatty acids that were already part of recon3D. Mind that it is at your own discretion wether you consider the deregulated proteins as a suitable up-stream input.

We are activelly working on incorporating more lipid reaction informations but it will take some more time as it is more chalenging that regular metabolic reactions. If you have a lipid reaction network that you trust already in the format of COSMOS meta PKN, then you can append it and use it as well.

**Comment by narmadabc** [comment]
Thank you very much for the response Aurelien
