### ISSUE TITLE
problem installing from github on windows

### ISSUE THREAD

**Issue by adugourd** [saezlab/cosmosR#5]
It works well when i install on Mac, but on windows I get this error :
Installing package into ‘C:/Users/omish/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'cosmos' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'cosmos'
    finding HTML links ... done
    binarize_with_sign                      html  
    check_CARNIVAL_options                  html  
    check_COSMOS_inputs                     html  
    check_gene_names                        html  
    check_inputs_for_CARNIVAL               html  
    check_network_data_coverage             html  
    convert_ensembl_to_entrezid             html  
    convert_genesymbols_to_entrezid         html  
    cosmos_data                             html  
    default_CARNIVAL_options                html  
    finding level-2 HTML links ... done

Rd warning: C:/Users/omish/AppData/Local/Temp/Rtmpc1BlW3/R.INSTALL84c259e5e56/cosmos/man/default_CARNIVAL_options.Rd:11: missing link 'CARNIVAL::runCARNIVAL'
    discretize_input                        html  
    filter_pkn_expressed_genes              html  
    filter_transcriptional_regulations      html  
    format_COSMOS_results                   html  
    get_TF_activity_from_CARNIVAL           html  
    keep_controllable_neighbours            html  
    keep_observable_neighbours              html  
    limit_string_vec                        html  
    load_meta_pkn                           html  
    load_tf_regulon_dorothea                html  
    load_tf_regulon_dorothea_omnipath       html  
    new_cosmos_data                         html  
    prepare_metabolomics_data               html  
Rd warning: C:/Users/omish/AppData/Local/Temp/Rtmpc1BlW3/R.INSTALL84c259e5e56/cosmos/man/prepare_metabolomics_data.Rd:15: missing link 'load_meta_pkn()'
    preprocess_COSMOS_core                  html  
Rd warning: C:/Users/omish/AppData/Local/Temp/Rtmpc1BlW3/R.INSTALL84c259e5e56/cosmos/man/preprocess_COSMOS_core.Rd:70: missing link 'default_CARNIVAL_options()'
    preprocess_COSMOS_metabolism_to_signaling
                                            html  
Rd warning: C:/Users/omish/AppData/Local/Temp/Rtmpc1BlW3/R.INSTALL84c259e5e56/cosmos/man/preprocess_COSMOS_metabolism_to_signaling.Rd:62: missing link 'default_CARNIVAL_options()'
    preprocess_COSMOS_signaling_to_metabolism
                                            html  
Rd warning: C:/Users/omish/AppData/Local/Temp/Rtmpc1BlW3/R.INSTALL84c259e5e56/cosmos/man/preprocess_COSMOS_signaling_to_metabolism.Rd:62: missing link 'default_CARNIVAL_options()'
    print.cosmos_data                       html  
    process_CARNIVAL_results                html  
    runCARNIVAL_wrapper                     html  
Rd warning: C:/Users/omish/AppData/Local/Temp/Rtmpc1BlW3/R.INSTALL84c259e5e56/cosmos/man/runCARNIVAL_wrapper.Rd:20: missing link 'CARNIVAL::runCARNIVAL'
Rd warning: C:/Users/omish/AppData/Local/Temp/Rtmpc1BlW3/R.INSTALL84c259e5e56/cosmos/man/runCARNIVAL_wrapper.Rd:22: missing link 'CARNIVAL::runCARNIVAL'
Rd warning: C:/Users/omish/AppData/Local/Temp/Rtmpc1BlW3/R.INSTALL84c259e5e56/cosmos/man/runCARNIVAL_wrapper.Rd:24: missing link 'CARNIVAL::runCARNIVAL'
    run_COSMOS_metabolism_to_signaling      html  
Rd warning: C:/Users/omish/AppData/Local/Temp/Rtmpc1BlW3/R.INSTALL84c259e5e56/cosmos/man/run_COSMOS_metabolism_to_signaling.Rd:42: missing link 'preprocess_COSMOS'
Rd warning: C:/Users/omish/AppData/Local/Temp/Rtmpc1BlW3/R.INSTALL84c259e5e56/cosmos/man/run_COSMOS_metabolism_to_signaling.Rd:28: missing link 'default_CARNIVAL_options()'
    run_COSMOS_signaling_to_metabolism      html  
Error: C:/Users/omish/AppData/Local/Temp/Rtmpc1BlW3/R.INSTALL84c259e5e56/cosmos/man/run_COSMOS_signaling_to_metabolism.Rd:14: Bad \link text
* removing 'C:/Users/omish/Documents/R/win-library/4.0/cosmos'
Error: Failed to install 'cosmos' from GitHub:
  (converted from warning) installation of package ‘C:/Users/omish/AppData/Local/Temp/RtmpuOziHB/file4e984c9542b1/cosmos_0.1.5.tar.gz’ had non-zero exit status

My session info :
- Session info ----------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 4.0.0 (2020-04-24)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_Germany.1252        
 ctype    English_Germany.1252        
 tz       Europe/Berlin               
 date     2020-11-11                  

- Packages --------------------------------------------------------------------------------------------------------------
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.0)
 backports     1.1.7   2020-05-13 [1] CRAN (R 4.0.0)
 callr         3.5.1   2020-10-13 [1] CRAN (R 4.0.3)
 cli           2.0.2   2020-02-28 [1] CRAN (R 4.0.0)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 4.0.0)
 curl          4.3     2019-12-02 [1] CRAN (R 4.0.3)
 desc          1.2.0   2018-05-01 [1] CRAN (R 4.0.2)
 devtools    * 2.3.2   2020-09-18 [1] CRAN (R 4.0.3)
 digest        0.6.25  2020-02-23 [1] CRAN (R 4.0.0)
 ellipsis      0.3.1   2020-05-15 [1] CRAN (R 4.0.2)
 fansi         0.4.1   2020-01-08 [1] CRAN (R 4.0.0)
 fs            1.5.0   2020-07-31 [1] CRAN (R 4.0.3)
 glue          1.4.1   2020-05-13 [1] CRAN (R 4.0.2)
 magrittr      1.5     2014-11-22 [1] CRAN (R 4.0.0)
 memoise       1.1.0   2017-04-21 [1] CRAN (R 4.0.3)
 pkgbuild      1.1.0   2020-07-13 [1] CRAN (R 4.0.3)
 pkgload       1.1.0   2020-05-29 [1] CRAN (R 4.0.2)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.0.2)
 processx      3.4.4   2020-09-03 [1] CRAN (R 4.0.3)
 ps            1.3.3   2020-05-08 [1] CRAN (R 4.0.2)
 R6            2.4.1   2019-11-12 [1] CRAN (R 4.0.0)
 remotes       2.2.0   2020-07-21 [1] CRAN (R 4.0.3)
 rlang         0.4.8   2020-10-08 [1] CRAN (R 4.0.3)
 rprojroot     1.3-2   2018-01-03 [1] CRAN (R 4.0.2)
 rstudioapi    0.11    2020-02-07 [1] CRAN (R 4.0.2)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.3)
 testthat      2.3.2   2020-03-02 [1] CRAN (R 4.0.2)
 usethis     * 1.6.3   2020-09-17 [1] CRAN (R 4.0.3)
 withr         2.2.0   2020-04-20 [1] CRAN (R 4.0.2)

[1] C:/Users/omish/Documents/R/win-library/4.0
[2] C:/Program Files/R/R-4.0.0/library

**Comment by gabora** [comment]
please check the most recent update. It should have fixed this issue.
